### ISSUE TITLE
Compatibility with koa-logger

### ISSUE THREAD

**Issue by edevil** [emartech/cls-adapter#1]
[koa-logger](https://github.com/koajs/logger) is a Koa middleware that calls a user supplied callback at the start and end of requests, so as to print information such as latency, status code, etc.

When the callback is called at the beginning of the request we have access to the cls context. However, when we are called at the end this context is not there. This is because the callback is called in the context of a "finished" or "close" event on  `ctx.res`.  [Relevant code](https://github.com/koajs/logger/blob/master/index.js#L93).

I've made it work by altering the module code:
```
const namespace = cls.createNamespace();
res.once('finish', namespace.bind(onfinish));
```

Is there any way to do just from my app side?

**Comment by blacksonic** [comment]
Merged the pull request, now it is released with version 1.2.0
